fix: fix bugs
nnslvp/coinmore-site pull request #17
Opened 2024-05-23 11:17 UTC by AndrewMatsiash

ТАСКИ
![Снимок экрана 2024-05-23 в 14 06 40](https://github.com/nnslvp/coinmore-site/assets/74107101/0e9eafe2-272a-434f-8be7-35c195a146b8)

результат 
![Снимок экрана 2024-05-23 в 14 15 33](https://github.com/nnslvp/coinmore-site/assets/74107101/2f2e630d-b1b9-4f79-8be8-6786b0257b95)
![Снимок экрана 2024-05-23 в 14 15 57](https://github.com/nnslvp/coinmore-site/assets/74107101/7e81352c-ea84-41b1-b9fb-c3ae1800719b)
![Снимок экрана 2024-05-23 в 14 16 41](https://github.com/nnslvp/coinmore-site/assets/74107101/72a3130e-278b-4d49-be9c-a484668b58b9)

2024-05-23 11:56 UTC, nnslvp commented on assets/js/main.js
> +  e.stopPropagation();
выравнивание

2024-05-23 11:56 UTC, nnslvp commented on assets/js/pages/coin-page.js
> +	e.preventDefault();
выравниване

2024-05-23 11:56 UTC, nnslvp commented on assets/sass/_header.scss
> +  box-shadow: 0px .25rem .625rem 0rem #00000040;
выравнивание

2024-05-23 11:56 UTC, nnslvp commented on assets/sass/components/_input.scss
> +// }
?

2024-05-23 11:57 UTC, nnslvp requested changes
Делай плз код ревью перед запросом ревью

2024-05-24 09:23 UTC, AndrewMatsiash commented on assets/js/main.js
> +  e.stopPropagation();
исправил

2024-05-24 09:23 UTC, AndrewMatsiash commented on assets/js/pages/coin-page.js
> +	e.preventDefault();
исправил

2024-05-24 09:23 UTC, AndrewMatsiash commented on assets/sass/_header.scss
> +  box-shadow: 0px .25rem .625rem 0rem #00000040;
сделал

2024-05-24 09:24 UTC, AndrewMatsiash commented on assets/sass/components/_input.scss
> +// }
убрал

2024-05-24 13:57 UTC, nnslvp approved these changes

2024-05-24 13:58 UTC, merged