Bugfix/fix bugs page statistics
nnslvp/coinmore-site pull request #19
Opened 2024-05-27 11:24 UTC by AndrewMatsiash

![Снимок экрана 2024-05-27 в 14 18 15](https://github.com/nnslvp/coinmore-site/assets/74107101/1a15cc0d-ce21-4f01-8753-d4eaa411d274)
<img width="1541" alt="Снимок экрана 2024-05-27 в 14 20 37" src="https://github.com/nnslvp/coinmore-site/assets/74107101/3b436752-2a07-4ae1-92fb-f0ce8a9dbc38">
<img width="628" alt="Снимок экрана 2024-05-27 в 14 21 01" src="https://github.com/nnslvp/coinmore-site/assets/74107101/f854c9d2-072b-4461-b9f2-beb36172485c">
<img width="1642" alt="Снимок экрана 2024-05-27 в 14 22 38" src="https://github.com/nnslvp/coinmore-site/assets/74107101/dc9c88ae-61e6-4b44-be86-2c706999e632">
<img width="1571" alt="Снимок экрана 2024-05-27 в 14 22 46" src="https://github.com/nnslvp/coinmore-site/assets/74107101/47a21c51-c76d-452e-929c-a17bbbc7fd0e">
<img width="507" alt="Снимок экрана 2024-05-27 в 14 23 35" src="https://github.com/nnslvp/coinmore-site/assets/74107101/14db82e8-17c7-427a-8b52-481d7b8d7298">

2024-05-27 12:11 UTC, nnslvp requested changes

2024-05-27 12:11 UTC, nnslvp commented on layouts/coin/statistics.html
> +      const COIN_SYMBOL = {{.Params.coin_symbol }}
выравнивание

2024-05-27 12:15 UTC, AndrewMatsiash commented on layouts/coin/statistics.html
> +      const COIN_SYMBOL = {{.Params.coin_symbol }}
исправил

2024-05-27 12:32 UTC, nnslvp requested changes

2024-05-27 12:32 UTC, nnslvp commented on assets/js/pages/coin-page.js
> +	console.log(profitHistoryWeek, profitHistoryDay);
?

2024-05-27 12:32 UTC, nnslvp commented on assets/js/pages/statistics-page.js
> +				console.error('Error:', error);
info или log, так как ошибка обработанная

2024-05-27 12:50 UTC, AndrewMatsiash commented on assets/js/pages/coin-page.js
> +	console.log(profitHistoryWeek, profitHistoryDay);
удалил

2024-05-27 12:50 UTC, AndrewMatsiash commented on assets/js/pages/statistics-page.js
> +				console.error('Error:', error);
сделал

2024-05-27 13:27 UTC, nnslvp commented on assets/js/pages/instructions-page.js
> -showPings();
Либо все комментируй либо все удаляй

2024-05-27 14:28 UTC, nnslvp requested changes

2024-05-27 14:28 UTC, nnslvp commented on assets/js/pages/statistics-page.js
> +
```suggestion
```

2024-05-27 14:28 UTC, nnslvp commented on assets/js/show-data-functions.js
> +}
EOF

2024-05-28 14:25 UTC, AndrewMatsiash commented on assets/js/pages/instructions-page.js
> -showPings();
удалил

2024-05-28 14:26 UTC, AndrewMatsiash commented on assets/js/show-data-functions.js
> +}
исправил

2024-05-28 15:23 UTC, nnslvp commented on assets/js/api.js
> +    return response.json();
тут выравнивание 2 пробела в других местах 4

2024-05-29 09:36 UTC, AndrewMatsiash commented on assets/js/api.js
> +    return response.json();
сделал

2024-05-29 10:11 UTC, AndrewMatsiash commented on assets/js/pages/statistics-page.js
> +
убрал

2024-05-29 12:22 UTC, nnslvp approved these changes

2024-05-29 12:25 UTC, merged