Bugfix/does not show daily hashrate chart
nnslvp/coinmore-site pull request #38
Opened 2024-06-12 12:51 UTC by AndrewMatsiash

<img width="296" alt="Снимок экрана 2024-06-12 в 15 50 36" src="https://github.com/nnslvp/coinmore-site/assets/74107101/110d08b9-66a4-44f4-b71e-247f89f9a17d">
таски небольшие по изменениям, я их обьеденил в один пуулл
<img width="833" alt="Снимок экрана 2024-06-12 в 15 42 46" src="https://github.com/nnslvp/coinmore-site/assets/74107101/e5d1bb82-3b48-4380-910d-982029b4502c">
<img width="1053" alt="Снимок экрана 2024-06-12 в 15 47 29" src="https://github.com/nnslvp/coinmore-site/assets/74107101/cb932cf9-b119-42c9-9b3b-2d1cfa9577b6">
график за день не появляется, так как приходят пустой массив
<img width="484" alt="Снимок экрана 2024-06-12 в 15 23 01" src="https://github.com/nnslvp/coinmore-site/assets/74107101/e744311d-e72b-442c-b612-3e8a151f3692">
статистика отображается
<img width="1558" alt="Снимок экрана 2024-06-12 в 15 49 15" src="https://github.com/nnslvp/coinmore-site/assets/74107101/d718a0f1-9c58-441a-9305-50360d321255">

2024-06-12 14:57 UTC, nnslvp commented on assets/js/pages/statistics-page.js
> +  INPUT_MIN_PAYOUTS.value = minPayoutsValue;
проверяй выравнивание переде создаем ПРа

2024-06-12 15:56 UTC, AndrewMatsiash commented on assets/js/pages/statistics-page.js
> +  INPUT_MIN_PAYOUTS.value = minPayoutsValue;
сделал

2024-06-13 14:03 UTC, nnslvp requested changes

2024-06-13 14:03 UTC, nnslvp commented on assets/sass/pages/_Statistics-page.scss
> +  pointer-events: initial;
выравниванике

2024-06-13 14:42 UTC, AndrewMatsiash commented on assets/sass/pages/_Statistics-page.scss
> +  pointer-events: initial;
сделал

2024-06-13 14:51 UTC, nnslvp approved these changes

2024-06-13 15:04 UTC, merged