feat:add default coin select depending on the  page coin
nnslvp/coinmore-site pull request #41
Opened 2024-06-17 15:27 UTC by AndrewMatsiash

2024-06-18 10:26 UTC, nnslvp requested changes

2024-06-18 10:26 UTC, nnslvp commented on assets/js/pages/calculator-page.js
> +	targetValue: COIN ?? 'alephium',
по дефолту монета не должна быть выбрана

2024-06-18 10:26 UTC, nnslvp commented on assets/js/pages/coin-page.js
> +	localStorage.setItem('pageCoin', COIN);
Я бы передавал через урл, localstorage это слишком

2024-06-18 13:17 UTC, AndrewMatsiash commented on assets/js/pages/calculator-page.js
> +	targetValue: COIN ?? 'alephium',
убрал

2024-06-18 13:19 UTC, AndrewMatsiash commented on assets/js/pages/coin-page.js
> +	localStorage.setItem('pageCoin', COIN);
сделал так, чтобы в урле появилась монета, раньше у нас была одна прямая ссылка, в котрой не было монеты
<img width="1246" alt="Снимок экрана 2024-06-18 в 16 15 40" src="https://github.com/nnslvp/coinmore-site/assets/74107101/4a508554-c048-4aae-ad1c-fef459b2e943">
<img width="1148" alt="Снимок экрана 2024-06-18 в 16 10 25" src="https://github.com/nnslvp/coinmore-site/assets/74107101/a4e8afdb-95de-4c98-bb0f-f2ca987a6c49">
<img width="1153" alt="Снимок экрана 2024-06-18 в 16 09 48" src="https://github.com/nnslvp/coinmore-site/assets/74107101/5e91d1a1-90e1-4d7e-9796-69d7f1747481">

2024-06-20 12:36 UTC, nnslvp requested changes

2024-06-20 12:36 UTC, nnslvp commented on layouts/_default/calculator.html
> +        const COIN = {{ $pageCoin.Params.coin_name }};
Старница калькулятора будет одна для всех монет,  не нужно создавать новую страницу под каждую монету.

Добавь параметр coin в урл а на странице монеты прочтай его через JS

2024-06-20 14:07 UTC, AndrewMatsiash commented on layouts/_default/calculator.html
> +        const COIN = {{ $pageCoin.Params.coin_name }};
cделал через  url

2024-06-20 14:44 UTC, nnslvp requested changes

2024-06-20 14:44 UTC, nnslvp commented on assets/js/pages/calculator-page.js
> +const COIN = window.location.search.split('=').at(1);
<img width="868" alt="image" src="https://github.com/nnslvp/coinmore-site/assets/65916399/9bcbe2be-8710-403b-be61-6393be416919">

2024-06-20 15:18 UTC, nnslvp approved these changes

2024-06-20 15:25 UTC, merged