Bugfix/need error handling from the server when changing the minimum payout
nnslvp/coinmore-site pull request #53
Opened 2024-06-26 12:54 UTC by AndrewMatsiash

2024-06-26 12:54 UTC, AndrewMatsiash commented
<img width="1059" alt="Снимок экрана 2024-06-26 в 15 52 20" src="https://github.com/nnslvp/coinmore-site/assets/74107101/304292b2-1bc9-41af-bfa3-fee4d3e598e1">
<img width="1051" alt="Снимок экрана 2024-06-26 в 15 52 45" src="https://github.com/nnslvp/coinmore-site/assets/74107101/fb4c5574-12e4-4ca0-805a-6db57483b61d">

2024-06-26 12:57 UTC, nnslvp commented
1)Конфликты
2)Покажи плз результат Ане

2024-06-26 13:35 UTC, AndrewMatsiash commented
<img width="383" alt="Снимок экрана 2024-06-26 в 16 34 18" src="https://github.com/nnslvp/coinmore-site/assets/74107101/2c053f78-1b82-44cf-a312-14cdbbd0cfb2">
<img width="378" alt="Снимок экрана 2024-06-26 в 16 34 43" src="https://github.com/nnslvp/coinmore-site/assets/74107101/e6bd67f3-fefd-4452-8156-00a4071176a9">

2024-06-26 14:02 UTC, nnslvp requested changes
Много проблем с форматированием

2024-06-26 14:02 UTC, nnslvp commented on assets/js/pages/statistics-page.js
> +	let	workers24h=[];
?

2024-06-26 14:02 UTC, nnslvp commented on assets/sass/_normalize.scss
> +  color: inherit;
?

2024-06-26 14:02 UTC, nnslvp commented on assets/sass/components/_toast.scss
> +  position: fixed;
в других файлах стиля другое форматирование

2024-06-26 14:02 UTC, nnslvp commented on assets/sass/pages/_Statistics-page.scss
> +    margin: 0;
?

2024-06-26 14:02 UTC, nnslvp commented on assets/sass/pages/_Statistics-page.scss
> +    width: 100%;
?

2024-06-27 10:03 UTC, AndrewMatsiash commented on assets/js/pages/statistics-page.js
> +	let	workers24h=[];
formatted

2024-06-27 10:03 UTC, AndrewMatsiash commented on assets/sass/_normalize.scss
> +  color: inherit;
formatted

2024-06-27 10:03 UTC, AndrewMatsiash commented on assets/sass/pages/_Statistics-page.scss
> +    margin: 0;
formatted

2024-06-27 10:06 UTC, AndrewMatsiash commented on assets/sass/pages/_Statistics-page.scss
> +    width: 100%;
formatted

2024-06-27 10:06 UTC, AndrewMatsiash commented on assets/sass/components/_toast.scss
> +  position: fixed;
formatted

2024-06-27 11:50 UTC, nnslvp requested changes

2024-06-27 11:50 UTC, nnslvp commented on assets/js/pages/statistics-page.js
> +	let rate = null;
```suggestion
	let rate;
```
Почему не так?

2024-06-27 11:50 UTC, nnslvp commented on assets/sass/components/_toast.scss
> +.toast {
в assets/sass/components/_input.scss другие отступы

2024-06-27 11:50 UTC, nnslvp commented on layouts/coin/statistics.html
> +                    <span id="balance">0</span>
думаю лучше ставить "-" или "N/A" так как 0 это обозначает что баланс 0 а "-" или "N/A" обозначает что баланс не получен

2024-06-27 11:50 UTC, nnslvp commented on layouts/coin/statistics.html
> +                    <span id="balance_usd">0 USD</span>
так же

2024-06-27 11:50 UTC, nnslvp commented on layouts/coin/statistics.html
> +    <p class="toast-text ">Oops, Wrong email or password!</p>
?

2024-06-27 11:51 UTC, AndrewMatsiash commented on assets/js/pages/statistics-page.js
> +	let rate = null;
Undefined дает nan в ui

2024-06-27 12:14 UTC, AndrewMatsiash commented on assets/sass/components/_toast.scss
> +.toast {
![Снимок экрана 2024-06-27 в 15 13 36](https://github.com/nnslvp/coinmore-site/assets/74107101/412d9468-4d5c-4051-916c-2857f7098b10)
![Снимок экрана 2024-06-27 в 15 14 23](https://github.com/nnslvp/coinmore-site/assets/74107101/5170dd49-a701-4c26-81f0-59f04ac9b548)

2024-06-27 12:15 UTC, AndrewMatsiash commented on assets/sass/components/_toast.scss
> +.toast {
одинаковые же

2024-06-27 12:21 UTC, nnslvp commented on assets/sass/components/_toast.scss
> +.toast {
Смотри в гите

2024-06-27 12:21 UTC, nnslvp commented on assets/sass/components/_toast.scss
> +.toast {
<img width="539" alt="image" src="https://github.com/nnslvp/coinmore-site/assets/65916399/2b2d1611-5258-4c3a-ae6f-21312d75d63e">
<img width="480" alt="image" src="https://github.com/nnslvp/coinmore-site/assets/65916399/4356f181-1c64-45f4-97e2-4a91ad9df69d">

2024-06-27 12:22 UTC, nnslvp commented on assets/sass/components/_toast.scss
> +.toast {
возможно где-то ты заюзал табы а гдето проблелы, юзай везде пробелы так как табы в разных сиситемах и редакторах отображаются по разному а пробелы одинаково

2024-06-27 13:06 UTC, AndrewMatsiash commented on layouts/coin/statistics.html
> +                    <span id="balance">0</span>
cделал -

2024-06-27 13:06 UTC, AndrewMatsiash commented on layouts/coin/statistics.html
> +                    <span id="balance_usd">0 USD</span>
added

2024-06-27 13:07 UTC, AndrewMatsiash commented on layouts/coin/statistics.html
> +    <p class="toast-text ">Oops, Wrong email or password!</p>
removed

2024-06-27 13:14 UTC, nnslvp requested changes

2024-06-27 13:14 UTC, nnslvp commented on assets/sass/components/_toast.scss
> +.toast {
Это еще надо привести к общему виду

2024-06-27 13:39 UTC, AndrewMatsiash commented on assets/sass/components/_toast.scss
> +.toast {
сделал 4 spaces

2024-06-27 14:02 UTC, nnslvp commented on assets/sass/components/_toast.scss
> +.toast {
@AndrewMatsiash 
<img width="474" alt="image" src="https://github.com/nnslvp/coinmore-site/assets/65916399/08e08983-c4b2-4e92-9c9f-4d476043bedc">
assets/sass/_icons.scss

2024-06-27 14:16 UTC, AndrewMatsiash commented on assets/sass/components/_toast.scss
> +.toast {
formatted

2024-06-28 16:18 UTC, nnslvp requested changes
Отступы и форматирование должно быть одинаково во одинаковых типах файлах как минимум, как я уже говорил, пока пишем как начали писать, потом приведем полностью весь проект к единому виду

2024-06-28 16:18 UTC, nnslvp commented on assets/sass/_icons.scss
> +    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='18' height='18' fill='none'%3E%3Cpath fill='%23fff' d='M9 .875C4.52.875.875 4.52.875 9S4.52 17.125 9 17.
В этом файле другие отступы

2024-06-28 16:18 UTC, nnslvp commented on assets/sass/pages/_Statistics-page.scss
> +      margin: 0;
В этом файле другие отступы

2024-06-29 18:03 UTC, nnslvp commented on assets/sass/components/_input.scss
> +    display: inline-block;
Тут было 4 пробела или таба, так и оставь, сделай везде одинаково, приводить проект к единому виду будем в отдельном ПРе

2024-07-01 21:38 UTC, nnslvp commented
<img width="582" alt="image" src="https://github.com/nnslvp/coinmore-site/assets/65916399/79f141b6-449c-4683-b5ee-e2c107716e11">
У тебя в одинаковых типах файлов разные отступы? Почему бы не поставить везде 4 как и было раньше? Почему новый код добавляешь с другими отступами?

2024-07-01 21:42 UTC, nnslvp requested changes

2024-07-01 21:42 UTC, nnslvp commented on assets/sass/components/_toast.scss
> +  cursor: pointer;
Тут один пробел отступ??))))

2024-07-01 21:42 UTC, nnslvp commented on assets/sass/components/_toast.scss
> +    flex: 1;
тут четыре пробела отступ

2024-07-01 21:42 UTC, nnslvp commented on assets/sass/main.scss
>  	animation: fadeIn 0.5s ease-in-out forwards;
Тут таблуляция отступ, вот так же ты начал форматировать, почему не продолжаешь делать так как начал изначально?

2024-07-02 10:54 UTC, mtshdev commented on assets/sass/_icons.scss
> +    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='18' height='18' fill='none'%3E%3Cpath fill='%23fff' d='M9 .875C4.52.875.875 4.52.875 9S4.52 17.125 9 17.
сделал 4 пробела

2024-07-02 10:55 UTC, mtshdev commented on assets/sass/pages/_Statistics-page.scss
> +      margin: 0;
сделал 4 пробела

2024-07-02 10:56 UTC, mtshdev commented on assets/sass/components/_input.scss
> +    display: inline-block;
сделал 4 пробела

2024-07-02 11:00 UTC, mtshdev commented on assets/sass/components/_toast.scss
> +    flex: 1;
сделал

2024-07-02 11:00 UTC, mtshdev commented on assets/sass/main.scss
>  	animation: fadeIn 0.5s ease-in-out forwards;
сделал везде 4

2024-07-02 11:02 UTC, mtshdev approved these changes

2024-07-02 13:22 UTC, nnslvp requested changes

2024-07-02 13:22 UTC, nnslvp commented on assets/sass/components/_input.scss
> +    border: 0.0625rem solid rgb(175, 184, 191);
Почему тут меняешь? Тут же было все в порядке

2024-07-02 13:22 UTC, nnslvp commented on assets/sass/components/_input.scss
> +    display: inline-block;
@mtshdev Помоему был таб а не 4 пробела

2024-07-02 13:22 UTC, nnslvp commented on assets/sass/components/_table-servers.scss
> +			content: attr(data) ":";
Не делай лишних изменений

2024-07-02 13:22 UTC, nnslvp commented on assets/sass/components/_custom-select.scss
> +	&[data-index="-1"] {
не делай лишних изменений, задача не об этом

2024-07-02 13:22 UTC, nnslvp commented on assets/sass/components/_custom-select.scss
> +	content: "";
лишнее изменение

2024-07-02 13:22 UTC, nnslvp commented on assets/sass/components/_toast.scss
> +    flex: 1;
Я имел ввиду что у тебя везеде таб а тут 4 пробела

2024-07-02 13:22 UTC, nnslvp commented on assets/sass/main.scss
>  	animation: fadeIn 0.5s ease-in-out forwards;
@mtshdev сделай плз как изначально было

2024-07-02 14:01 UTC, nnslvp commented on assets/js/pages/statistics-page.js
> +
```suggestion
```

2024-07-02 14:01 UTC, nnslvp commented on assets/js/chart.js
> -					text: CHART_TITLE.hashrate,
Почему?

2024-07-02 14:01 UTC, nnslvp commented on assets/js/api.js
> +				throw new Error(err.errors[0]);
Ошибок может быть несколько а ты берешь одну, верно я понимаю код?

2024-07-02 14:01 UTC, nnslvp commented on assets/sass/_fonts.scss
> +		url("/fonts/Poppins-Bold.woff2") format("woff2"),
Похоже что лишнее изменение

2024-07-02 14:03 UTC, mtshdev commented on assets/js/api.js
> +				throw new Error(err.errors[0]);
да, вывожу лишь первую, но да, бэк отдает массив

2024-07-02 14:03 UTC, mtshdev commented on assets/sass/_fonts.scss
> +		url("/fonts/Poppins-Bold.woff2") format("woff2"),
откатился и убрал все лишние

2024-07-02 14:04 UTC, mtshdev commented on assets/sass/_fonts.scss
> +		url("/fonts/Poppins-Bold.woff2") format("woff2"),
запушил

2024-07-02 14:28 UTC, mtshdev commented on assets/js/chart.js
> -					text: CHART_TITLE.hashrate,
тут он не нужен дефолтный

2024-07-02 14:28 UTC, mtshdev commented on assets/js/chart.js
> -					text: CHART_TITLE.hashrate,
для каждого графика он свой

2024-07-02 14:32 UTC, nnslvp commented on assets/js/api.js
> +				throw new Error(err.errors[0]);
Надо выводить все, их может быть несколько

2024-07-02 14:34 UTC, mtshdev commented on assets/js/pages/statistics-page.js
> +
убрал

2024-07-02 15:05 UTC, mtshdev commented on assets/js/api.js
> +				throw new Error(err.errors[0]);
вывожу все

2024-07-02 15:06 UTC, mtshdev commented on assets/sass/components/_input.scss
> +    border: 0.0625rem solid rgb(175, 184, 191);
убрал все лишнее

2024-07-02 15:06 UTC, mtshdev commented on assets/sass/components/_table-servers.scss
> +			content: attr(data) ":";
убрал все лишнее

2024-07-02 15:06 UTC, ghost commented on assets/sass/components/_custom-select.scss
> +	content: "";
убрал все лишнее

2024-07-02 22:36 UTC, nnslvp requested changes

2024-07-02 22:36 UTC, nnslvp commented on assets/js/pages/statistics-page.js
> +			} else if (results[0].status === 'rejected') {
вынеси все results[N] в отдельные пероеменные чтобы понимать какой индекс что содержит

2024-07-03 12:53 UTC, nnslvp commented on assets/js/pages/statistics-page.js
> +			} else if (results[0].status === 'rejected') {
Мб что-то вроде:

```
const [
  currencyInfo,
  payouts1h,
  payouts24h,
  balance,
  payoutsWeek,
  hashrate1h,
  hashrate24h,
  historyWalletWeek,
  historyWalletDayR,
  historyWorkersDay,
  fee
] = result;

```

2024-07-03 14:25 UTC, mtshdev commented on assets/js/pages/statistics-page.js
> +			} else if (results[0].status === 'rejected') {
added

2024-07-04 19:46 UTC, nnslvp approved these changes

2024-07-05 09:56 UTC, merged