feat: add save search wallet for every coin
nnslvp/coinmore-site pull request #78
Opened 2024-07-25 12:15 UTC by AndrewMatsiash

2024-07-25 20:41 UTC, nnslvp requested changes

2024-07-25 20:41 UTC, nnslvp commented on assets/js/pages/statistics-page.js
> +    saveWalletsToLocalStorage(COIN, walletFromParams);
Предлагаю сохранять значения так: localStorage.setItem(wallet_${coin}, wallet);
Так код будет проще

2024-07-26 11:23 UTC, nnslvp commented on assets/js/helpers.js
> +    return wallet;
<img width="260" alt="image" src="https://github.com/user-attachments/assets/e1c8fdb4-12d5-4ce6-a995-bccc6b44ddd5">

Для чего этот if?

2024-07-26 11:36 UTC, AndrewMatsiash commented on assets/js/pages/statistics-page.js
> +    saveWalletsToLocalStorage(COIN, walletFromParams);
did it

2024-07-26 11:40 UTC, AndrewMatsiash commented on assets/js/helpers.js
> +    return wallet;
по сути да, не нужен он тут, убрал

2024-07-26 11:48 UTC, nnslvp requested changes

2024-07-26 11:48 UTC, nnslvp commented on assets/js/pages/statistics-page.js
> +      const wallet = walletsFromLocalStorage;
Для чего эта переменная? Думаю можно обойтись без нее

2024-07-29 09:33 UTC, AndrewMatsiash commented on assets/js/pages/statistics-page.js
> +      const wallet = walletsFromLocalStorage;
исправил

2024-07-29 12:08 UTC, nnslvp approved these changes

2024-07-29 15:07 UTC, merged